# [벡터화]
### 벡터 생성하기

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([1,2])

In [ ]:
a

array([1, 2])

In [ ]:
a.shape # 종벡터

(2,)

In [ ]:
len(a)

2

### 거리 구하기

In [ ]:
a = np.array([1,2])
b = np.array([2,2])
c = np.array([-3, -3])

In [ ]:
# 벡터 a의 길이 구하기
np.linalg.norm(a)

np.float64(2.23606797749979)

1. 유클리디안 거리

norm() 함수를 이용해서 두 벡터 사이의 유클리디안 거리 구하기

In [ ]:
print(np.linalg.norm(b-a))
print(np.linalg.norm(c-a))

1.0
6.4031242374328485

scipy에서 distance 모듈에서 제공되는 함수를 이용한 유클리디안 거리 계산

In [ ]:
import scipy.spatial.distance as dst

In [ ]:
dst.euclidean(a,b)

np.float64(1.0)

In [ ]:
dst.euclidean(a,c)

np.float64(6.4031242374328485)

2. 시티블록 거리

linalg 모듈의 norm() 함수를 이용한 L1-norm 거리 계산

In [ ]:
np.linalg.norm(c-a, 1)

np.float64(9.0)

scipy: 시티블록 거리 (L1 norm) 계산하기

In [ ]:
dst.cityblock(a,b)

np.int64(1)

In [ ]:
dst.cityblock(a,c)

np.int64(9)

3. Hamming distance

In [ ]:
d = np.array([1,0,0])
e = np.array([1,1,0])

In [ ]:
dst.hamming(d,e)

np.float64(0.3333333333333333)

4. Jaccard distance

In [ ]:
dst.jaccard(d,e) # 확인

np.float64(0.5)

# Cosine similarity

#### 내적 (dot product)

In [ ]:
a = np.array([1,2])
b = np.array([2,2])
np.dot(a,b)

np.int64(6)

In [ ]:
# 코사인 유사도
np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

np.float64(0.9486832980505138)

#### cosine distance

In [ ]:
dst.cosine(a,b)

np.float64(0.05131670194948623)

In [ ]:
1-np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

np.float64(0.05131670194948623)

# 예제 데이터 사용해 보기

In [ ]:
import pandas as pd
data = data = pd.DataFrame({
    '관측치': [1, 2, 3],
    '나이': [30, 33, 55],
    '직장 경력': [1, 2, 25]
})

In [ ]:
data

   관측치  나이  직장 경력
0    1  30      1
1    2  33      2
2    3  55     25

In [ ]:
data_np = data.values

In [ ]:
data_np

array([[ 1, 30,  1],
       [ 2, 33,  2],
       [ 3, 55, 25]])

In [ ]:
# 첫 번째 관측치에 대한 벡터
data_np[0]

array([ 1, 30,  1])

In [ ]:
# 첫 번째 벡터와 두 번째 벡터 간의 유클리디안 거리
np.linalg.norm(data_np[1]-data_np[0])

np.float64(3.3166247903554)

In [ ]:
# 첫 번째 벡터와 세 번째 벡터 간의 유클리디안 거리
np.linalg.norm(data_np[2]-data_np[0])

np.float64(34.713109915419565)

In [ ]:
# 첫 번째 벡터와 두 번째 벡터 간의 코사인 세타
np.dot(data_np[0],data_np[1])/(np.linalg.norm(data_np[0])*np.linalg.norm(data_np[1]))

np.float64(0.9992629882143517)

In [ ]:
# 첫 번째 벡터와 세 번째 벡터 간의 코사인 세타
np.dot(data_np[0],data_np[2])/(np.linalg.norm(data_np[0])*np.linalg.norm(data_np[2]))

np.float64(0.923650102953477)

# [doc_vectorization]

In [ ]:
# 텍스트 데이터 (말뭉치)
# 아래 TEXT 변수의 각 원소가 하나의 문서를 의미합니다.
# CountVectorizer나 TfidfVectorizer 클래스를 이용하기 위해서는
# 각 문서는 단어들로 구성된 하나의 문자열값으로 저장되어야 합니다.
TEXT = ['banana apple apple eggplant',
        'orange carrot banana eggplant',
        'apple carrot banana banana',
        'orange banana grape'
]

# CountVectorizer 이용하기

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer # frequency based DTM

# min_df=2: 단어가 최소한 2개 이상의 문서에 등장
# max_df=0.8: 단어가 전체 문서의 80% 이상에서 등장하면 벡터에서 제외
# ngram_range=(1,1): 단어 단위의 토큰만 추출(유니그램)
tf_vectorizer = CountVectorizer(min_df=2, max_df=0.8, ngram_range=(1,1))
tf_features = tf_vectorizer.fit_transform(TEXT)

In [ ]:
print(tf_features)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	2
  (0, 2)	1
  (1, 2)	1
  (1, 3)	1
  (1, 1)	1
  (2, 0)	1
  (2, 1)	1
  (3, 3)	1

In [ ]:
features = np.array(tf_features.todense())

In [ ]:
features

array([[2, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 0, 1]])

In [ ]:
# 첫 번째 문서의 벡터
features[0]

array([2, 0, 1, 0])

In [ ]:
features[1]

array([0, 1, 1, 1])

In [ ]:
# 단어들의 이름 확인하기
feature_names = tf_vectorizer.get_feature_names_out()
print(feature_names)

['apple' 'carrot' 'eggplant' 'orange']

In [ ]:
import pandas as pd
df = pd.DataFrame(data=features, columns=feature_names)
df

   apple  carrot  eggplant  orange
0      2       0         1       0
1      0       1         1       1
2      1       1         0       0
3      0       0         0       1

문서들 간의 유사도 계산해 보기

In [ ]:
# 첫 번째 문서와 두 번째 문서 간 유클리디안 거리
print(np.linalg.norm(features[1]-features[0]))

2.449489742783178

In [ ]:
# 첫 번째 문서와 두 번째 문서 간 코사인 유사도
print(np.dot(features[0],features[1])/(np.linalg.norm(features[0])*np.linalg.norm(features[1])))

0.2581988897471611

# TfidfVectorizer 이용하기

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer # tf-idf based DTM
tfidf_vectorizer = TfidfVectorizer(min_df=2, max_df=0.8, ngram_range=(1,1))
tfidf_features = tfidf_vectorizer.fit_transform(TEXT)

In [ ]:
print(tfidf_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	0.8944271909999159
  (0, 2)	0.4472135954999579
  (1, 2)	0.5773502691896257
  (1, 3)	0.5773502691896257
  (1, 1)	0.5773502691896257
  (2, 0)	0.7071067811865475
  (2, 1)	0.7071067811865475
  (3, 3)	1.0

In [ ]:
tfidf_features = np.array(tfidf_features.todense())
tfidf_features

array([[0.89442719, 0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.57735027],
       [0.70710678, 0.70710678, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [ ]:
# 첫 번째 문서의 벡터
tfidf_features[0]

array([0.89442719, 0.        , 0.4472136 , 0.        ])

In [ ]:
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()
df = pd.DataFrame(data=tfidf_features, columns=tfidf_feature_names)
df

      apple    carrot  eggplant   orange
0  0.894427  0.000000  0.447214  0.00000
1  0.000000  0.577350  0.577350  0.57735
2  0.707107  0.707107  0.000000  0.00000
3  0.000000  0.000000  0.000000  1.00000

In [ ]:
# 벡터의 길이 = 1
np.linalg.norm(tfidf_features[0])

np.float64(0.9999999999999999)

In [ ]:
# 첫 번째 문서와 두 번째 문서 간의 유클리디안 거리 구하기
np.linalg.norm(tfidf_features[1]-tfidf_features[0])

np.float64(1.2180321098007547)

In [ ]:
# 첫 번째 문서와 두 번째 문서 간 코사인 유사도
print(np.dot(tfidf_features[0],tfidf_features[1])/(np.linalg.norm(tfidf_features[0])*np.linalg.norm(tfidf_features[1])))

0.25819888974716115