## 시리즈 개요

In [9]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [10]:
print(s.name)
print(s.index)
print(s.values)
print(s.shape)
print(s.size)

first
RangeIndex(start=0, stop=6, step=1)
[ 1.  3.  5. nan  6.  8.]
(6,)
6

## 시리즈 인덱싱과 슬라이싱

In [11]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [12]:
s[1]

3.0

In [13]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [14]:
s[2] = 50
s

0     1.0
1     3.0
2    50.0
3     NaN
4     6.0
5     8.0
Name: first, dtype: float64

In [15]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [17]:
s.index = list('abcdef')
s

a     1.0
b     3.0
c    50.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [18]:
s['a']

1.0

In [19]:
s[0]

<ipython-input-19-c9c96910e542>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

1.0

In [20]:
s[1:5]

b     3.0
c    50.0
d     NaN
e     6.0
Name: first, dtype: float64

In [21]:
s['a':'d']

a     1.0
b     3.0
c    50.0
d     NaN
Name: first, dtype: float64

In [22]:
s1 = s[1:4]
s1

b     3.0
c    50.0
d     NaN
Name: first, dtype: float64

In [23]:
s1[0]

<ipython-input-23-bfed54b371ac>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

3.0

In [24]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [25]:
s.index = np.arange(1, 7)
s

1     1.0
2     3.0
3    50.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [27]:
s[1]

1.0

In [29]:
s[1:4] # 원 첨자인 0에서부터 참조

2     3.0
3    50.0
4     NaN
Name: first, dtype: float64

## 시리즈 고급 인덱싱

In [34]:
age = pd.Series([9, 17, 32, 45, 65, 98], index=list('abcdef'), name='age')
age

a     9
b    17
c    32
d    45
e    65
f    98
Name: age, dtype: int64

In [35]:
age[ [1, 3, 5] ]

<ipython-input-35-f4f4e44c80e2>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1, 3, 5]]

b    17
d    45
f    98
Name: age, dtype: int64

In [36]:
age[ ['a', 'c'] ]

a     9
c    32
Name: age, dtype: int64

In [38]:
age['f'] # 항목을 반환

98

In [40]:
age[ ['f'] ] # 항목을 갖는 시리즈를 반환

f    98
Name: age, dtype: int64

## 불리안 인덱싱

In [41]:
s = pd.Series([3, 6, -3, 0, -4, 8, -7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64

In [42]:
s > 0

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [43]:
s[ s > 0 ]

0    3
1    6
5    8
dtype: int64

In [44]:
s[ s%2 == 0]

1    6
3    0
4   -4
5    8
dtype: int64

종료