5주차

In [1]:
import numpy as np
import pandas as pd

In [4]:
df_raw = pd.DataFrame({'var1' : [1, 2, 1],
           'var2' : [2, 3, 2],
           'var3' : [10, 20, 30]})

df_raw

   var1  var2  var3
0     1     2    10
1     2     3    20
2     1     2    30

In [5]:
df_new = df_raw.copy()

df_new

   var1  var2  var3
0     1     2    10
1     2     3    20
2     1     2    30

In [6]:
id(df_new) == id(df_raw)

False

In [7]:
df_new.rename(columns={'var2' : 'v2'})

   var1  v2  var3
0     1   2    10
1     2   3    20
2     1   2    30

In [8]:
df_new

   var1  var2  var3
0     1     2    10
1     2     3    20
2     1     2    30

In [9]:
df_new.rename(columns={'var2' : 'v2'}, inplace=True)

In [10]:
df_new

   var1  v2  var3
0     1   2    10
1     2   3    20
2     1   2    30

In [11]:
df_new.rename(index={0:'x', 1:'y', 2:'z'}, inplace=True)

df_new

   var1  v2  var3
x     1   2    10
y     2   3    20
z     1   2    30

In [13]:
df = pd.DataFrame({'A':[1, 2, 3], 'B':[4, 5, 6]})

df.rename(columns={'A':'a', 'B':'c'})

   a  c
0  1  4
1  2  5
2  3  6

In [14]:
df

   A  B
0  1  4
1  2  5
2  3  6

파생변수 생성

In [ ]:
df = pd.DataFrame({'var1':[3, 5, 2],
                   ''})