In [1]:
import numpy as np
import pandas as pd

문제 4

In [2]:
df1 = pd.DataFrame({
    'var1' : [1, 2, 1],
    'var2' : [2, 3, 2]})

df1.rename(columns={'var2' : 'v2'}, inplace=True)
df1.rename(index={0 : 'x', 2 : 'y'}, inplace=True)

df1

   var1  v2
x     1   2
1     2   3
y     1   2

문제 5

In [6]:
mpg = pd.read_csv('./data/mpg.csv')

mpg['size'] = np.where((mpg['category'] == 'compact') | 
                       (mpg['category'] == '2seater'), 'small', 'large')

mpg.head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,size
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,small
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,small
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,small
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,small
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,small

In [12]:
mpg['size'] = np.where(mpg['category'].isin(['compact', '2seater']), 'small', 'large')

mpg.head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,size
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,small
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,small
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,small
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,small
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,small

문제 6

In [15]:
mpg.groupby('drv').agg(mean_city = ('cty', 'mean'),
                       mean_hwy = ('hwy', 'mean'))

     mean_city   mean_hwy
drv
4    14.330097  19.174757
f    19.971698  28.160377
r    14.080000  21.000000

---

In [18]:
mpg.query('hwy > 40.5')

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,size
212,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact,small
221,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact,large
222,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,large

---

In [21]:
mpg.assign(mpg_mean = (mpg.hwy + mpg.cty) / 2)

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,size,mpg_mean
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,small,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,small,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,small,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,small,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,small,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,large,23.5
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,large,25.0
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,large,21.0
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,large,22.0
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,large,21.5

문제 7

In [46]:
df1 = pd.DataFrame({
    'sub' : ['AI', 'Python', 'Java'],
    'score' : [80, 77, 99]
})

df2 = pd.DataFrame({
    'sub' : ['AI', 'Python', 'C'],
    'book' : [30000, 28000, 25000]
})

In [47]:
df1.merge(df2)

      sub  score   book
0      AI     80  30000
1  Python     77  28000

In [52]:
df1.merge(df2).shape

(2, 3)

In [53]:
df1.merge(df2).shape[1]

3

---

In [28]:
df1.merge(df2, how='left')

      sub  score     book
0      AI     80  30000.0
1  Python     77  28000.0
2    Java     99      NaN

In [26]:
df1.merge(df2, how='left')['book'][1]

np.float64(28000.0)

---

In [29]:
df1.merge(df2, how='outer')

      sub  score     book
0      AI   80.0  30000.0
1       C    NaN  25000.0
2    Java   99.0      NaN
3  Python   77.0  28000.0

In [30]:
df1.merge(df2, how='outer').iloc[2, 0]

'Java'

---

In [32]:
df1.merge(df2, how='cross')

    sub_x  score   sub_y   book
0      AI     80      AI  30000
1      AI     80  Python  28000
2      AI     80       C  25000
3  Python     77      AI  30000
4  Python     77  Python  28000
5  Python     77       C  25000
6    Java     99      AI  30000
7    Java     99  Python  28000
8    Java     99       C  25000

In [31]:
len(df1.merge(df2, how='cross'))

9

문제 8

In [37]:
d = pd.DataFrame({
    'carat' : [0.90, np.nan, 0.58, 1.51, np.nan],
    'cut' : ['Premium', 'Ideal', np.nan, 'Premium', np.nan],
    'color' : ['E', 'H', 'G', 'G', np.nan],
    'clarity' : ['VS2', 'SI2', np.nan, 'VS2', 'VVS2']
})

d

   carat      cut color clarity
0   0.90  Premium     E     VS2
1    NaN    Ideal     H     SI2
2   0.58      NaN     G     NaN
3   1.51  Premium     G     VS2
4    NaN      NaN   NaN    VVS2

In [38]:
d.dropna()

   carat      cut color clarity
0   0.90  Premium     E     VS2
3   1.51  Premium     G     VS2

In [54]:
d.dropna().shape

(2, 4)

In [35]:
d.dropna().shape[0]

2

---

In [40]:
d.isna()

   carat    cut  color  clarity
0  False  False  False    False
1   True  False  False    False
2  False   True  False     True
3  False  False  False    False
4   True   True   True    False

In [41]:
# 행을 기준으로 연산
# 0행 F, 1행 T, 2행 F, 3행 F, 4행 T
# T가 하나라도 존재함으로 True
d.isna().any()

carat      True
cut        True
color      True
clarity    True
dtype: bool

In [39]:
d.isna().any().sum()

np.int64(4)

---

In [44]:
d.isna()

   carat    cut  color  clarity
0  False  False  False    False
1   True  False  False    False
2  False   True  False     True
3  False  False  False    False
4   True   True   True    False

In [42]:
# 열을 기준으로 연산
# carat열 F, cut열 F, color열 F, clarity열 F
# T가 한개도 없어서 False
d.isna().any(axis=1)

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [43]:
d.isna().any(axis=1).sum()

np.int64(3)